/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BayRouteImport } from './routes/bay'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as ShoreRouteImport } from './routes/shore'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BayRoute = BayRouteImport.update({
  id: '/bay',
  path: '/bay',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoreRoute = ShoreRouteImport.update({
  id: '/shore',
  path: '/shore',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bay': typeof BayRoute
  '/roster': typeof RosterRoute
  '/shore': typeof ShoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bay': typeof BayRoute
  '/roster': typeof RosterRoute
  '/shore': typeof ShoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bay': typeof BayRoute
  '/roster': typeof RosterRoute
  '/shore': typeof ShoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bay' | '/roster' | '/shore'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bay' | '/roster' | '/shore'
  id: '__root__' | '/' | '/bay' | '/roster' | '/shore'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BayRoute: typeof BayRoute
  RosterRoute: typeof RosterRoute
  ShoreRoute: typeof ShoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bay': {
      id: '/bay'
      path: '/bay'
      fullPath: '/bay'
      preLoaderRoute: typeof BayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shore': {
      id: '/shore'
      path: '/shore'
      fullPath: '/shore'
      preLoaderRoute: typeof ShoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BayRoute: BayRoute,
  RosterRoute: RosterRoute,
  ShoreRoute: ShoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
